name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup environment
      run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda create -q -n tests-environment
          conda activate tests-environment
          conda env update -f environment.yml
          python setup.py install

