name: CI

on: [push]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: false
    #- name: Checkout LFS objects
    #  run: git lfs checkout
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup environment
      run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda create -q -n vtam
          source activate vtam
          conda env update -f environment.yml
    - name: Run tests
      env:
        CI: true
      run: |
        # activate conda env
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate vtam
        vsearch --version
        cutadapt --version
        blastn -version
        python -m unittest discover -v -f

