name: Run tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
      with:
        fs: true
    - name: Pull LFS objects
      run: git lfs pull
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup environment
      run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda create -q -n vtam
          source activate vtam
          conda env update -f environment.yml
    - name: Run tests
      env:
        CI: true
      run: |
        # activate conda env
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate vtam
        vsearch --version
        cutadapt --version
        blastn -version
        python -m unittest discover -v -f

